 - name: Setting up prerequisite
   yum: name=yum-utils state=installed

 - name: Enabling Docker Yum Repository
   shell: 'yum-config-manager --enable extras'
   
 - name: Uninstalling old versions of Docker
   yum: name={{ item }} state=absent
   with_items:
    - docker
    - docker-ce
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
     
 - name: Setting up Docker-CE Repository prerequisite
   yum: name={{ item }} state=installed
   with_items:
    - device-mapper-persistent-data
    - lvm2
    
 - name: Setting up Docker-CE Repository
   shell: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'

 - name: Setting up addtional rpms needed for RHEL based systems
   yum: name={{ item }} state=installed
   with_items:
    - http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.21-1.el7.noarch.rpm
    - http://springdale.math.ias.edu/data/puias/unsupported/7/x86_64/pigz-2.3.4-1.sdl7.x86_64.rpm
   when: ansible_distribution == 'RedHat'
   
 - name: Installing Docker-CE Package
   yum: name=docker-ce state=latest
   
 - name: Starting & Enabling Docker
   service: 
    name: docker 
    state: started
    enabled: yes
   
